from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Copy test error examples for visual review.")
    parser.add_argument(
        "--errors",
        default="outputs/modelos/random_forest_test_errors.csv",
        help="CSV generated by scripts/train_models.py.",
    )
    parser.add_argument("--out", default="outputs/erros/random_forest")
    parser.add_argument("--limit", type=int, default=10)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    errors = pd.read_csv(args.errors).head(args.limit)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    for idx, row in errors.iterrows():
        source = Path(row["image_path"])
        target = out_dir / f"{idx:02d}_true-{row['y_true']}_pred-{row['y_pred']}_{source.name}"
        shutil.copy2(source, target)
    print(f"Copied {len(errors)} error examples to {out_dir}")


if __name__ == "__main__":
    main()
